# Generated by Django 4.1.4 on 2023-01-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance_status1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pids', models.IntegerField()),
                ('Pid_status', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Instance_status',
        ),
    ]
