# Generated by Django 4.1.4 on 2023-01-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_instance_status1_delete_instance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance_status2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pids', models.IntegerField()),
                ('Pid_status', models.CharField(max_length=30)),
                ('start_datetime', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Instance_status1',
        ),
    ]
