# Generated by Django 4.1.4 on 2023-01-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0003_instance_status2_delete_instance_status1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance_status2',
            name='start_datetime',
            field=models.DateTimeField(default=None),
        ),
    ]
