# Generated by Django 4.1.4 on 2023-01-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0005_instance_status2_stop_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pids', models.IntegerField()),
                ('Pid_status', models.CharField(max_length=30)),
                ('start_datetime', models.DateTimeField()),
                ('stop_datetime', models.DateTimeField(default=None)),
            ],
        ),
        migrations.DeleteModel(
            name='Instance_status2',
        ),
    ]
