# Generated by Django 4.1.4 on 2023-01-01 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Code', models.CharField(max_length=30)),
                ('Time_Frame', models.CharField(choices=[('Intraday', 'Intraday'), ('Positional', 'Positional')], max_length=30)),
                ('Type', models.CharField(choices=[('Short Volatility', 'Short Volatility'), ('Short Directional', 'Short Directional'), ('Long Directional', 'Long Directional'), ('Pattern System', 'Pattern System'), ('Calendar Spread', 'Calendar Spread'), ('Expiry', 'Expiry')], max_length=30)),
                ('Initialize_Time', models.TimeField()),
                ('Script', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy_Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Descrption', models.CharField(max_length=200)),
                ('Variable_Name', models.CharField(max_length=30)),
                ('Parameter_Type', models.CharField(choices=[('Number', 'Number'), ('Time', 'Time')], max_length=30)),
                ('Parameter_Value', models.CharField(default='', max_length=10)),
                ('Strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy_settings.strategy_details')),
            ],
        ),
        migrations.CreateModel(
            name='Add_Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exchange', models.CharField(choices=[('NSE', 'NSE'), ('BSE', 'BSE')], max_length=30)),
                ('Symbol', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=30)),
                ('is_Monday', models.BooleanField(default=False, verbose_name='Monday')),
                ('is_Tuesday', models.BooleanField(default=False, verbose_name='Tuesday')),
                ('is_Wednesday', models.BooleanField(default=False, verbose_name='Wednesday')),
                ('is_Thursday', models.BooleanField(default=False, verbose_name='Thursday')),
                ('is_Friday', models.BooleanField(default=False, verbose_name='Friday')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy_settings.strategy_details')),
            ],
        ),
    ]
