# Generated by Django 4.1.4 on 2023-01-02 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_Monday', models.BooleanField(default=False, verbose_name='Monday')),
                ('is_Tuesday', models.BooleanField(default=False, verbose_name='Tuesday')),
                ('is_Wednesday', models.BooleanField(default=False, verbose_name='Wednesday')),
                ('is_Thursday', models.BooleanField(default=False, verbose_name='Thursday')),
                ('is_Friday', models.BooleanField(default=False, verbose_name='Friday')),
                ('Initialize_Time', models.TimeField()),
                ('Terminate_Time', models.TimeField()),
                ('Parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy_settings.strategy_parameters')),
                ('Strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy_settings.strategy_details')),
                ('Symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy_settings.add_symbol')),
            ],
        ),
    ]
